export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const RESPONSE_MESSAGE = 'RESPONSE_MESSAGE';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';